"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var games_1 = require("../controllers/games");
var mediasRouter = express_1.Router();
mediasRouter.get("/games", games_1.getGames);
// mediasRouter.get("/genre-cast/:mediaId", getMediaGenreAndCast);
// mediasRouter.get("/watching", getMediaWatchingByUser);
// mediasRouter.post("/add-to-watching/:mediaId", addToWatchingByUser);
// mediasRouter.delete("/remove-from-watching/:mediaId", removeFromWatchingByUser);
// mediasRouter.get("/search", getMediasBySearch);
exports.default = mediasRouter;
